services:
  web:
    container_name: poke_python
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@db:5432/pokeweb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media

  db:
    container_name: poke_db
    image: postgres:17.5-alpine3.22
    environment:
      - POSTGRES_DB=pokeweb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: poke_redis
    image: redis:8.0.2-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.27.5-alpine
    container_name: poke_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
